"""
知识来源种子：登记适合纳入贵金属知识库的外部权威与研究来源。
"""
from __future__ import annotations

EXTERNAL_KNOWLEDGE_SOURCE_SEEDS = [
    {
        "title": "World Gold Council - Gold as a strategic asset 2026 edition",
        "source_type": "official_web",
        "location": "https://www.gold.org/goldhub/research/gold-strategic-asset-2026-edition",
        "author": "World Gold Council",
        "published_at": "2026-02-04",
        "trust_level": "official",
        "tags": ["gold", "macro", "allocation", "strategic"],
        "notes": "适合作为黄金长期配置、流动性、分散性与组合定位的基础框架。",
    },
    {
        "title": "World Gold Council - Gold Outlook 2026",
        "source_type": "official_web",
        "location": "https://www.gold.org/goldhub/research/gold-outlook-2026",
        "author": "World Gold Council",
        "published_at": "2025-12-09",
        "trust_level": "official",
        "tags": ["gold", "macro", "momentum", "drivers"],
        "notes": "可作为黄金年度驱动拆解来源，适合建立宏观驱动标签体系。",
    },
    {
        "title": "World Gold Council - Gold Demand Trends Full Year 2025",
        "source_type": "official_web",
        "location": "https://www.gold.org/goldhub/research/gold-demand-trends/gold-demand-trends-full-year-2025",
        "author": "World Gold Council",
        "published_at": "2026-01-29",
        "trust_level": "official",
        "tags": ["gold", "demand", "etf", "central_bank"],
        "notes": "适合作为黄金投资需求、ETF 流向与官方购金行为的事实底座。",
    },
    {
        "title": "World Gold Council - Central Banks in Gold Demand Trends Full Year 2025",
        "source_type": "official_web",
        "location": "https://www.gold.org/goldhub/research/gold-demand-trends/gold-demand-trends-full-year-2025/central-banks",
        "author": "World Gold Council",
        "published_at": "2026-01-29",
        "trust_level": "official",
        "tags": ["gold", "central_bank", "macro"],
        "notes": "适合作为央行购金持续性与中长期支撑逻辑的权威来源。",
    },
    {
        "title": "FRED - 10-Year TIPS Real Yield DFII10",
        "source_type": "official_data",
        "location": "https://fred.stlouisfed.org/series/dfii10",
        "author": "Federal Reserve Bank of St. Louis",
        "published_at": "",
        "trust_level": "official",
        "tags": ["macro", "real_yield", "gold"],
        "notes": "适合作为黄金机会成本与实际利率驱动的长期事实数据源。",
    },
    {
        "title": "CFTC - Commitments of Traders",
        "source_type": "official_data",
        "location": "https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm",
        "author": "CFTC",
        "published_at": "",
        "trust_level": "official",
        "tags": ["futures", "positioning", "gold", "silver"],
        "notes": "适合作为资金持仓、管理资金方向和拥挤度监控的标准来源。",
    },
    {
        "title": "CFTC - COMEX Gold COT Report",
        "source_type": "official_data",
        "location": "https://www.cftc.gov/dea/futures/deacmxsf.htm",
        "author": "CFTC",
        "published_at": "",
        "trust_level": "official",
        "tags": ["gold", "cot", "futures"],
        "notes": "适合作为黄金期货周度仓位结构的具体事实源。",
    },
    {
        "title": "CME Group - Gold & Silver Ratio Spread",
        "source_type": "exchange_education",
        "location": "https://www.cmegroup.com/education/courses/introduction-to-precious-metals/gold-and-silver-ratio-spread-trade.html",
        "author": "CME Group",
        "published_at": "",
        "trust_level": "exchange",
        "tags": ["gold", "silver", "ratio", "spread"],
        "notes": "适合作为金银比、跨品种价差和均值回归知识的正规交易所教育材料。",
    },
    {
        "title": "CME Group - Trading COMEX Gold and Silver",
        "source_type": "exchange_education",
        "location": "https://www.cmegroup.com/education/articles-and-reports/trading-comex-gold-and-silver.html",
        "author": "CME Group",
        "published_at": "",
        "trust_level": "exchange",
        "tags": ["gold", "silver", "futures", "spread"],
        "notes": "适合作为贵金属期货、价差交易和执行逻辑的补充来源。",
    },
    {
        "title": "Silver Institute - World Silver Survey 2025",
        "source_type": "industry_research",
        "location": "https://silverinstitute.org/world-silver-survey-2025/",
        "author": "Silver Institute",
        "published_at": "2025-04-16",
        "trust_level": "industry",
        "tags": ["silver", "industrial_demand", "pv", "automotive"],
        "notes": "适合作为白银工业需求、PV、汽车与供需缺口的产业事实来源。",
    },
    {
        "title": "Silver Institute - Silver Supply & Demand",
        "source_type": "industry_research",
        "location": "https://silverinstitute.org/silver-supply-demand/",
        "author": "Silver Institute",
        "published_at": "",
        "trust_level": "industry",
        "tags": ["silver", "supply", "demand", "deficit"],
        "notes": "适合作为白银供需缺口与库存逻辑的持续更新来源。",
    },
    {
        "title": "SPDR Gold Shares - Key Information",
        "source_type": "official_web",
        "location": "https://www.spdrgoldshares.com/usa/key-information",
        "author": "World Gold Trust Services",
        "published_at": "",
        "trust_level": "official",
        "tags": ["gold", "etf", "holdings", "gld"],
        "notes": "适合作为黄金 ETF 持仓、净值和跟踪机制的事实来源。",
    },
    {
        "title": "IG - What is a False Breakout and How Do You Avoid It?",
        "source_type": "broker_education",
        "location": "https://www.ig.com/en/trading-strategies/what-is-a-false-breakout-and-how-can-you-avoid-it--230130",
        "author": "IG",
        "published_at": "2023-01-30",
        "trust_level": "broker",
        "tags": ["breakout", "false_breakout", "risk_control"],
        "notes": "适合作为突破确认、假突破识别与风险控制的补充教育来源，需回测验证。",
    },
]
